/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente.Vistas;

import Cliente.Interfaces.ManejarEventos;

/**
 *
 * @author ja-za
 */
public class ClientePrincipal extends javax.swing.JFrame {

    private ManejarEventos manejador;
    /**
     * Creates new form ClientePrincipal
     * @param manejador
     */
    public ClientePrincipal(ManejarEventos manejador) {
        initComponents();
        this.manejador = manejador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLan = new javax.swing.JButton();
        lblTexto = new javax.swing.JLabel();
        btnOnline = new javax.swing.JButton();
        btnReglas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLan.setText("Buscar partida en LAN");
        btnLan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanActionPerformed(evt);
            }
        });

        lblTexto.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto.setText("Pong Online");

        btnOnline.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOnline.setText("Buscar partida online");

        btnReglas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReglas.setText("Reglas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTexto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReglas, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLan, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLan, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReglas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanActionPerformed
        manejador.iniciarCliente();
        lblTexto.setText("Esperando partida ....");
        btnLan.setEnabled(false);
        btnOnline.setEnabled(false);
        btnReglas.setEnabled(false);
    }//GEN-LAST:event_btnLanActionPerformed

    public void activar(){
        btnLan.setEnabled(true);
        btnOnline.setEnabled(true);
        btnReglas.setEnabled(true);
        lblTexto.setText("Pong Online");
        setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLan;
    private javax.swing.JButton btnOnline;
    private javax.swing.JButton btnReglas;
    private javax.swing.JLabel lblTexto;
    // End of variables declaration//GEN-END:variables
}
